package ru.j2dev.gameserver.model.base;

public class PlayerAccess {
    public int PlayerID;
    public boolean IsGM;
    public boolean CanUseGMCommand;
    public boolean CanAnnounce;
    public boolean CanBanChat;
    public boolean CanUnBanChat;
    public boolean CanChatPenalty;
    public int BanChatDelay = -1;
    public int BanChatMaxValue = -1;
    public int BanChatCountPerDay = -1;
    public int BanChatBonusId = -1;
    public int BanChatBonusCount = -1;
    public boolean CanSetCarma;
    public boolean CanCharBan;
    public boolean CanCharUnBan;
    public boolean CanBan;
    public boolean CanUnBan;
    public boolean CanTradeBanUnban;
    public boolean CanUseBanPanel;
    public boolean UseGMShop;
    public boolean CanDelete;
    public boolean CanKick;
    public boolean Menu;
    public boolean GodMode;
    public boolean CanEditChar;
    public boolean CanEditCharAll;
    public boolean CanEditPledge;
    public boolean CanViewChar;
    public boolean CanEditNPC;
    public boolean CanViewNPC;
    public boolean CanTeleport;
    public boolean CanRestart;
    public boolean MonsterRace;
    public boolean Rider;
    public boolean FastUnstuck;
    public boolean ResurectFixed;
    public boolean Door;
    public boolean Res;
    public boolean PeaceAttack;
    public boolean Heal;
    public boolean Unblock;
    public boolean UseInventory = true;
    public boolean UseTrade = true;
    public boolean CanAttack = true;
    public boolean CanEvaluate = true;
    public boolean CanJoinParty = true;
    public boolean CanJoinClan = true;
    public boolean UseWarehouse = true;
    public boolean UseShop = true;
    public boolean UseTeleport = true;
    public boolean BlockInventory;
    public boolean CanChangeClass;
    public boolean CanGmEdit;
    public boolean IsEventGm;
    public boolean CanReload;
    public boolean CanRename;
    public boolean CanJail;
    public boolean CanPolymorph;
}
